server:
  port: 9000
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest